AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Hola Mundo

Resources:
  HolaMundoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 3
      MemorySize: 128
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hola
            Method: get
